### PR TITLE
fix: public/non-public scopes

### LINKED ISSUE #67: Fix scopes in PipelineCompiler.java
Constructor should be public and the `commands` arraylist should be private

### PR DESCRIPTION
**Pull request by haval0**
resolves #67

The constructor is made public, the commands field is no longer public

## Checklist before requesting review

-   [x] Feature/fix PRs should add one atomic (as small as possible) feature or
        fix
-   [x] If your PR adds a feature or fix it also needs to add or modify at least
        one test
-   [x] All code in your PR needs to have been formatted
-   [x] The merge commit title should follow our commit prefix convention of
        either "feat", "fix", "chore", "doc", or "refactor"
-   [x] The merge commit body should reference at least one issue
-   [x] The code compiles and all the tests pass

### CODE REVIEW

**Comment by haval0** [comment]
Should perhaps be a `chore: ` instead of a `fix: ` PR

File: app/src/main/java/ciserver/PipelineCompiler.java [hunk 1]
```diff
@@ -9,43 +9,43 @@
...
-			e.printStackTrace();
-			return PipelineStatus.Fail;
-		} catch (InterruptedException e) {
-			e.printStackTrace();
-			return PipelineStatus.Fail;
-		}
-
-		return PipelineStatus.Ok;
-	}
+    final ArrayList<String> commands = new ArrayList<>();
```
Comment (psoder) [inline app/src/main/java/ciserver/PipelineCompiler.java]: Also final doesn't really do anything here since it just prevents reassignment, but it doesn't hurt so ¯\\\_(ツ)_/¯

```suggestion
    private final ArrayList<String> commands = new ArrayList<>();
```

**Review by psoder — CHANGES_REQUESTED** [review]

File: app/src/main/java/ciserver/PipelineCompiler.java (hunk 1 above)
Comment (didrikmunther) [reply app/src/main/java/ciserver/PipelineCompiler.java]: Variables should automatically be immutable, don't try to change my mind about this :^)

**Review by didrikmunther — APPROVED** [review]
LGTM
